server:
  port: 80
  tomcat:
    accesslog:
      buffered: true
      directory: /usr/local/projects/site/logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.site.POJO

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.222.224.182:3306/my_site?serverTimezone=Asia/Shanghai
      username: root
      password: Fan@13205763766
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    com.example.site.DAO: INFO
  file:
    path: /usr/local/projects/site/info-log/
    name: tomcat.log

qiniu:
  accesskey: "BaYnS_HE5c4NjVq_r0NxpbNBaQScNRahIVRTYhx3"
  serectkey: "2AqwWLBVXuytx-6cHCbAxTBdyZPcVrzHBqXzfstC"
  bucket: "evanhydecblog"
  cdn:
    url: "http://qiniu.tuffydog.site"



